name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BRANCH_NAME: ${{ secrets. BRANCH_NAME }}

jobs:
  Build-and-test-the-Code:
    runs-on: ubuntu-22.04
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    name: Build and test the React code

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        node-version:
          - 16.x

    steps:
      - name: Checkout out code in workflow
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node dependencies
        run: npm ci

      - name: Test the code
        run: npm test

      - name: Build the code
        run: npm run build --if-present

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
