name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        node-version:
          - 14.x

    runs-on: ubuntu-22.04
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    name: Build and test the React code

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout out code in workflow
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node dependencies
        run: npm ci --legacy-peer-deps

      - name: Test the code
        run: npm test

      - name: Build the code
        run: CI=false && npm run build --if-present

  deploy:
    runs-on: ubuntu-22.04
    needs: [build]

    steps:
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
